export default function PrivacyPolicy() {
  return (
    <div className="container mx-auto rounded-2xl p-6">
      <h1 className="mb-1 text-2xl font-bold">
        Privacy Policy for Flashcard Generator
      </h1>
      <p className="mb-6 text-sm text-gray-500">Last updated: July 10, 2025</p>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">1. Interpretation</h2>
        <p>
          The words with capitalized initials have specific meanings defined
          under the &quot;Definitions&quot; section. These definitions apply
          throughout this Privacy Policy, whether in singular or plural form.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">2. Definitions</h2>
        <ul className="list-inside list-disc space-y-1">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service.
          </li>
          <li>
            <strong>Service</strong> refers to the Flashcard Generator website,
            accessible at https://flashcard.jeromejalandoon.online
          </li>
          <li>
            <strong>Personal Data</strong> means any information that relates to
            an identified or identifiable individual.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>Google OAuth</strong> means the authentication system
            provided by Google using the OAuth 2.0 protocol.
          </li>
          <li>
            <strong>Session Cookies</strong> are cookies set for the duration of
            an active login session and deleted when the session ends.
          </li>
          <li>
            <strong>We</strong>, <strong>Us</strong>, or <strong>Our</strong>{" "}
            refers to Flashcard Generator.
          </li>
          <li>
            <strong>You</strong> or <strong>Your</strong> means the individual
            accessing or using the Service.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">3. Introduction</h2>
        <p>
          Welcome to Flashcard Generator (“we,” “us,” or “our”). This Service is
          provided free of charge.This Privacy Policy explains how we handle
          information when you use our non-commercial website (the “Service”),
          which enables you to generate AI-powered flashcards. By accessing or
          using the Service, you agree to the collection and use of information
          as described here. This Privacy Policy explains how we handle
          information when you use our non-commercial website (the “Service”),
          which enables you to generate AI-powered flashcards. By accessing or
          using the Service, you agree to the collection and use of information
          as described here.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">
          4. Information We Collect
        </h2>
        <ul className="list-inside list-disc space-y-1">
          <li>
            <strong>Google OAuth Information:</strong>
            <ul className="ml-4 list-inside list-decimal">
              <li>
                When You sign in via Google OAuth, we only request and
                temporarily access Your basic profile information, including:
              </li>
              <ul className="ml-6 list-inside list-disc">
                <li>Your Google account name</li>
                <li>Your Google account email address</li>
                <li>Your Google profile picture URL (if available)</li>
              </ul>
              <li>
                We do <strong>not</strong> collect any additional data from Your
                Google account.
              </li>
            </ul>
          </li>
          <li>
            <strong>Automatically Collected Data:</strong>
            <ul className="ml-6 list-inside list-disc">
              <li>
                We do <strong>not</strong> use analytics or tracking services.
              </li>
              <li>
                We do <strong>not</strong> place cookies, except for minimal
                Session Cookies strictly necessary to keep You logged in during
                Your visit.
              </li>
            </ul>
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">
          5. How We Use Your Information
        </h2>
        <ul className="list-inside list-disc space-y-1">
          <li>
            <strong>Authentication:</strong> To verify Your identity and grant
            You access to the Service via Google OAuth.
          </li>
          <li>
            <strong>Session Management:</strong> To maintain Your logged-in
            session securely during Your visit.
          </li>
          <li>
            <strong>Providing the Service:</strong> To enable the flashcard
            generation features tied to Your account.
          </li>
        </ul>
        <p>
          We do <strong>not</strong> use Your information for marketing,
          advertising, profiling, or any purpose other than operating and
          improving the Service.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">6. Data Retention</h2>
        <ul className="list-inside list-disc space-y-1">
          <li>
            Your Google profile information is <strong>not</strong> stored
            permanently on our servers.
          </li>
          <li>
            We retain only the minimal information in encrypted session storage
            for the duration of Your active session.
          </li>
          <li>
            Once You log out or Your session expires, all session data is
            deleted.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">7. Your Rights</h2>
        <ul className="list-inside list-disc space-y-1">
          <li>
            <strong>Right to Access:</strong> You may request a copy of any
            Personal Data we hold about You.
          </li>
          <li>
            <strong>Self-Service Data Deletion:</strong> You can delete your
            personal account data at any time by using the “Delete Account”
            option in your account settings.
          </li>
          <li>
            <strong>Right to Deletion of Personal Data:</strong> Alternatively,
            you may request that we delete all Personal Data we have collected.
            Because we only retain session-based data that is deleted upon
            logout or session expiration, any residual personal account data can
            be permanently removed upon request.
          </li>
          <li>
            <strong>Service Content Retention:</strong> Flashcards and other
            content you generate using the Service are considered non-personal
            Service content. These items are retained to ensure continuity and
            availability of the Service and cannot be automatically deleted
            through a personal data deletion request.
          </li>
          <li>
            <strong>Content Removal Requests:</strong> If you wish for specific
            flashcards or generated content to be removed, please contact us as
            described in the “Contact Us” section. Removal of Service content
            will be assessed on a case-by-case basis but is not guaranteed.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">
          8. Sharing Your Information
        </h2>
        <ul className="list-inside list-disc space-y-1">
          <li>
            We do <strong>not</strong> share, sell, rent, or trade Your personal
            information with any third parties, except:
          </li>
          <ul className="ml-6 list-inside list-disc">
            <li>
              <strong>Legal Requirements:</strong> If required by law or to
              comply with a valid legal process.
            </li>
            <li>
              <strong>Service Providers:</strong> We do not engage any external
              service providers for analytics, marketing, or data storage.
            </li>
          </ul>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">9. Third-Party Services</h2>
        <ul className="list-inside list-disc space-y-1">
          <li>
            <strong>Google OAuth:</strong>
            <ul className="ml-6 list-inside list-disc">
              <li>Our authentication relies on Google’s OAuth 2.0 system.</li>
              <li>
                Google’s collection and use of information You provide is
                governed by Google’s Privacy Policy. Please review it here:
                https://policies.google.com/privacy
              </li>
            </ul>
          </li>
          <li>
            We do <strong>not</strong> integrate any other third-party services,
            analytics tools, or advertising networks.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">10. Security</h2>
        <p>
          We implement industry-standard security measures to protect Your
          information during transmission (e.g., HTTPS/TLS) and in session
          storage. However, no method of transmission or storage is 100% secure.
          We cannot guarantee absolute security.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">11. Children’s Privacy</h2>
        <p>
          Our Service is not directed to children under 13. We do not knowingly
          collect Personal Data from anyone under 13. If You believe we may have
          collected information from a child under 13, please contact us, and we
          will promptly delete that information.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-semibold">
          12. Changes to This Privacy Policy
        </h2>
        <p>
          We may update this Privacy Policy from time to time. When we do, we
          will post the revised version here with an updated “Last updated”
          date. Your continued use of the Service after any changes constitutes
          acceptance of the updated policy.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold">13. Contact Us</h2>
        <p>
          If You have any questions or concerns about this Privacy Policy, or to
          exercise Your rights, please contact us at:
        </p>
        <ul className="ml-6 list-inside list-disc">
          <li>
            Email:{" "}
            <a
              href="mailto:your-email@example.com"
              className="text-blue-500 underline"
            >
              jerome.jalandoon@gmail.com
            </a>
          </li>
        </ul>
      </section>
    </div>
  );
}
